[green_agent]
endpoint = "http://127.0.0.1:9009"
cmd = "python Arena/src/server.py --host 127.0.0.1 --port 9009"

[[participants]]
role = "oss-120b-1"
endpoint = "http://127.0.0.1:9019"
cmd = "python Agent/src/server.py --host 127.0.0.1 --port 9019"

[[participants]]
role = "oss-120b-2"
endpoint = "http://127.0.0.1:9018"
cmd = "python Agent/src/server.py --host 127.0.0.1 --port 9018"

[config]
MaxRuns = 3